const TYPES = {
  GET_DATA: 'GET_DATA',
  UPDATE_SEARCH_INPUT: 'UPDATE_SEARCH_INPUT',
  FILTER_BY_SKU: 'FILTER_BY_SKU',
  VERIFY_VALIDATION_INPUT: 'VERIFY_VALIDATION_INPUT',
  SHOW_FILTERED_PRODUCTS: 'SHOW_FILTERED_PRODUCTS',
  RESET_INPUT: 'RESET_INPUT',
};

export default TYPES;
